### PR TITLE
Add gitter chat on index page

### PR DESCRIPTION
**Pull request by davydovanton**
Hey, I added [sidecar](https://sidecar.gitter.im) to our index page. I can add this to all pages but I think it will be unnecessary. What do you think?

### How it works
hanami-sidecar

/cc @jodosha @cllns @hanami/contributors

### CODE REVIEW

**Comment by cllns** [comment]
I like it! :)

**Comment by AlfonsoUceda** [comment]
I like it but I don't know if it will be used, can we know this?

**Comment by davydovanton** [comment]
@AlfonsoUceda I have no idea how we can know this. But we can revert this at any time.

**Comment by AlfonsoUceda** [comment]
Yeah, just made the question because of curiosity ;)

**Comment by davydovanton** [comment]
@AlfonsoUceda if we use google analytics we can create handler (or trigger) for this button I think

**Comment by jodosha** [comment]
@davydovanton I'm intrigued. Yes we use GA. Do we want to set a goal to measure the success of this experiment?

**Comment by pascalbetz** [comment]
I like the idea!

**Comment by davydovanton** [comment]
@jodosha so, I think it will be the interesting experience. And after that, we can say work this solution or not. I believe that it will be helpful for other projects like rom, dry, TRB, etc.

Maybe it will be good to add this button to all pages. For example:
You read a guide about something. Find some complicated part, and you can ask help in one click instead of opening a new page, finding gitter chat, etc. WDYT?

**Comment by jodosha** [comment]
@davydovanton I assumed that you wanted to add to all the pages.

**Comment by davydovanton** [comment]
Also. I have the idea for another issue. I think we can set click link counter for other links like Twitter, Github, etc. It will be helpful for understanding how often users use this links and maybe we will drop some links after this experiment.

**Comment by davydovanton** [comment]
As I said before it only on the index page. But I can add the button to other pages too. @jodosha do you think that we need to add this button to each page, yes?

**Comment by jodosha** [comment]
> But I can add the button to other pages too.

Yes, let's try for a month.

**Comment by jodosha** [comment]
> I think we can set click link counter for other links like Twitter, Github, etc. It will be helpful for understanding how often users use this links and maybe we will drop some links after this experiment.

Anything that helps to track how many people uses it. And possibly the percentage.

**Comment by davydovanton** [comment]
@jodosha yep, I'll create the issue for GA improvements. Okay?

**Comment by davydovanton** [comment]
Okay, I added sidecar button for all pages in our site 👍 
Let's try it 🎉

**Comment by AlfonsoUceda** [comment]
LGTM 👍

**Comment by davydovanton** [comment]
thanks for merge @AlfonsoUceda 👍

**Comment by AlfonsoUceda** [comment]
you welcome ;)

**Pull request merged**
