### PR TITLE
Add information about supporting link_to method

### PR DESCRIPTION
**Pull request by davydovanton**
Reference https://github.com/hanami/helpers/issues/48

/cc @joneslee85, @jodosha

### CODE REVIEW

**Comment by joneslee85** [comment]
How about adding another example for 1 2 link_to(s) to demo that we have to concatenate them

**Comment by davydovanton** [comment]
@joneslee85 yes, I like your idea :+1: 
I added more complicated example.

**Comment by jodosha** [comment]
@davydovanton @joneslee85 Merged, thank you all!

**Comment by davydovanton** [comment]
thanks you all :-1:

**Pull request merged**
