### PR TITLE
Added selection of `foreign key`

### PR DESCRIPTION
**Pull request by ilyario**

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
@ilyario thanks for this PR but I agree with @davydovanton, we don't need this change

**Comment by ilyario** [comment]
OK.
I thought that it was necessary to allocate a function, as in other paragraphs.

**Comment by cllns** [comment]
I'm actually in favor of this, if you change it to `foreign_key` (with the underscore).

`primary_key` has the code blocks around it, in the previous paragraph and `#column` has it in the next paragraph. We should be consistent :)

While you're at it , can you remove the leading `#` from `#column`? 

Are you OK with that, @AlfonsoUceda & @davydovanton?

**Comment by AlfonsoUceda** [comment]
@cllns :+1:

**Comment by davydovanton** [comment]
@cllns 👍 

@ilyario  could you fix it the small issue, and after that, I'll merge this changes? thank you!

**Comment by ilyario** [comment]
@davydovanton here are not edited locally, this recreate PR
see https://github.com/hanami/hanami.github.io/pull/348

**Comment by davydovanton** [comment]
@ilyario okay I'll close this PR

**Pull request closed without merging**
