### PR TITLE
Add logos for some Australian companies using Hanami

### PR DESCRIPTION
**Pull request by ZimbiX**
Depends on https://github.com/hanami/hanami.github.io/pull/571 - merge that first.

[As discussed in the Ruby AU Slack](https://rubyau.slack.com/archives/C039RN1PR/p1677910441230219).

### CODE REVIEW

**Comment by timriley** [comment]
Hi @ZimbiX, thanks for this :) 

Could you please update this so it's GreenSync only?

I think it would be best for representatives of the other companies to make their own submissions if they want their association with Hanami to be publicized here.

(I'm very happy to see GreenSync here though!)

**Comment by ZimbiX** [comment]
Fair enough. I can't speak on behalf of GreenSync either any more though, so I think I'll have to just close this then =\

**Comment by timriley** [comment]
@ZimbiX oh! Sorry about that, somehow I thought you were still there 😬

**Comment by ZimbiX** [comment]
No worries =P

**Pull request closed without merging**
