### PR TITLE
Add Algolia search

### PR DESCRIPTION
**Pull request by mbajur**
This PR introduces Algolia search to hanami guides.

lip-27-2018 12-19-56

Related to #449

### CODE REVIEW

**Comment by mbajur** [comment]
What's the status of that? I received a message from algolia team:

> It seems DocSearch is not used anymore on your website. At least, it had 0 searches in the last month. Do you need help in order to integrate it? Do you still want to keep it?
> 
> Please note, that DocSearch is a community project and associated resources are limited, so without answer from you within 10 days, your DocSearch crawler will be disabled.
> 
> Looking forward to hearing back from you soon,

**Comment by s-pace** [comment]
Awesome 🙏 , feel free to ping if you need anything 🚀

**Comment by cllns** [comment]
Thanks for doing this! I have a couple questions:
- @s-pace Outside of this specific issue, how long will it take to crawl when we release a new version? For example, we have a `1.3` release coming up soon. When it's merged, how long until the results can be in search results?
- @mbajur (and maybe @s-pace) Who's account is this API key associated with? If we have any problems, it'd be nice if we (the core team) can fix it ourselves. Can you add either the GitHub organization, or some of us to the Algolia account?

**Comment by AlfonsoUceda** [comment]
Hi folks, thanks for this PR, can you answer @cllns questions? I would love to have this feature.

**Comment by s-pace** [comment]
👋 
Sorry, it was lost in my notifications.

@cllns 

We crawl your website every 24h and you do not need to bother about the crawling time (really fast)

If you want to add a new PR, you will need to add it from your configuration. We can also fetch it from your website thanks to javascript but it would be more clear to PR it. Changes will be available as soon as we have merge your PR (within 72h worst case scenario)

**Comment by s-pace** [comment]
I will reply for @mbajur 

The search [key is user agnostic. It is a read only one. If you want to edit something, you will need to PR it or you can run it on your own](https://community.algolia.com/docsearch/documentation/docsearch-scraper/overview/) with your own algolia account.

We do provide the full algolia analytics for free for your DocSearch index. You can send the email addresses of the people you want us to add via docsearch@algolia.com

**Comment by AlfonsoUceda** [comment]
thanks @mbajur and @s-pace, let's merge this PR and see how it works ;)

**Comment by AlfonsoUceda** [comment]
@s-pace I can't see any result when searching, do we need to wait or we can force the reindex of the documents?

**Comment by AlfonsoUceda** [comment]
@s-pace I can already see results ;)

**Comment by s-pace** [comment]
You needed to PR it. I have done it for you this time

**Comment by AlfonsoUceda** [comment]
@s-pace thanks!, just for the record, we need to do it here https://github.com/algolia/docsearch-configs, isn't?

**Comment by s-pace** [comment]
CC [this commit](https://github.com/algolia/docsearch-configs/commit/63b153531e98a71e4e7fa5f637f9f1cf36f0d3a4)

**Pull request merged**
