### PR TITLE
Update documentation for repository last and second methods

### PR DESCRIPTION
**Pull request by davydovanton**
Reference to https://github.com/hanami/model/issues/380

/cc @hanami/documentation @cllns @jodosha

### CODE REVIEW

**Comment by cllns** [comment]
Thanks for remembering to do this @davydovanton <3

I committed some changes to this branch. I think they help explain the rationale behind recommending `one` vs `first`. 

**But** I don't think this should be merged now:
- someone else should check my changes for accuracy, and
- we should add note about how `first` and `last` are different (returning `Hash` vs entity). I feel like that was the impetus behind this change, and we don't directly address it. Instead, we tell people how to avoid it.

As a bigger question, before `1.0.0.rc1`, should we:
1. remove `first` and `last` from `Hanami::Repository` altogether? Instead we could encourage `limit` & `one` (and, optionally, `order`). @solnic [mentioned considering removing](https://github.com/rom-rb/rom-sql/issues/64#issuecomment-275660022) `first` and `last` from `rom-sql`, and if we can be ahead of this change, it could be good :) If so, should combine with 3.
2. change `first` implementation in `Hanami::Repository` to `root.limit(1).one` (and `last` to `root.limit(1).reverse.one`), to avoid the Hash/entity issue https://github.com/hanami/model/issues/380#issuecomment-280253302
3. add a warning to `first` and `last`, discouraging their use, in favor or `limit` and `one`?

If it's too late for any of these, that's fine. Just thought I'd bring it up :)
@hanami/core @jodosha

**Comment by davydovanton** [comment]
@cllns 
raw

**Comment by AlfonsoUceda** [comment]
@cllns @davydovanton good work ;)

The documentation is fine for me but as @cllns said:
> we should add note about how first and last are different (returning Hash vs entity). I feel like that was the impetus behind this change, and we don't directly address it. Instead, we tell people how to avoid it.

This would be perfect :)

**Comment by AlfonsoUceda** [comment]
@cllns @davydovanton is there a chance to finish this?

**Pull request merged**
