### PR TITLE
WIP: Doc: fix code in Guides/1.1/Architecture/Interactors

### PR DESCRIPTION
**Pull request by sutonea**
see: https://github.com/hanami/hanami.github.io/issues/435

### CODE REVIEW

**Comment by sutonea** [comment]
I'm investigating `Hanami::Interactor`.

Hanami::Interactor.included
---------------

```ruby
    # Override for <tt>Module#included</tt>.
    #
    # @since 0.3.5
    # @api private
    def self.included(base)
      super

      base.class_eval do
        extend ClassMethods
      end
    end
```

Above from: https://github.com/hanami/utils/blob/6a3bc0d3e93ef2949752c4dd79a7623b74478a05/lib/hanami/interactor.rb#L140-L150

Hanami:: Interactor::ClassMethods#method_added
------------------
```ruby
    def method_added(method_name)
      super
      return unless method_name == :call

      if instance_method(:call).arity.zero?
        prepend Hanami::Interactor::LegacyInterface
      else
        prepend Hanami::Interactor::Interface
      end
    end
```

Above from: https://github.com/hanami/utils/blob/6a3bc0d3e93ef2949752c4dd79a7623b74478a05/lib/hanami/interactor.rb#L571-L580

I'll read `Hanami::Interactor::LegacyInterface` and `Hanami::Interactor::Interface` .

**Comment by sutonea** [comment]
Hanami::Interactor::LegacyInterface
------------

**initialize**

```ruby
      def initialize(*args)
        super
      ensure
        @__result = ::Hanami::Interactor::Result.new
      end
```

Above from: https://github.com/hanami/utils/blob/6a3bc0d3e93ef2949752c4dd79a7623b74478a05/lib/hanami/interactor.rb#L156-L186

**call**

```ruby
      def call
        _call { super }
      end
```

Above from: https://github.com/hanami/utils/blob/6a3bc0d3e93ef2949752c4dd79a7623b74478a05/lib/hanami/interactor.rb#L188-L263



Hanami::Interactor::Interface
-----------

**initialize** : none

**call**

```ruby
      def call(*args)
        @__result = ::Hanami::Interactor::Result.new
        _call(*args) { super }
      end
```

Above from: https://github.com/hanami/utils/blob/6a3bc0d3e93ef2949752c4dd79a7623b74478a05/lib/hanami/interactor.rb#L287-L357

**Comment by sutonea** [comment]
`ArgumentError: wrong number of arguments (given 0, expected 1)` from `yield` :

```ruby
      # @api private
      # @since 1.1.0
      def _call(*args)
        catch :fail do
          validate!(*args)
          yield
        end


        _prepare!
      end
```

Above from:

https://github.com/hanami/utils/blob/6a3bc0d3e93ef2949752c4dd79a7623b74478a05/lib/hanami/interactor.rb#L366

**Comment by sutonea** [comment]
I fixed `spec/bookshelf/interactors/add_book_spec.rb` in my sample project ( bookshelf ), and ran `bundle exec rake test`.

Another error was occured.......

```
$ bundle exec rake test
Run options: --seed 51777

# Running:

.E..............S..

Finished in 0.135238s, 140.4931 runs/s, 266.1974 assertions/s.

  1) Error:
AddBook#test_0001_succeeds:
NameError: undefined local variable or method `be_a_success' for #<#<Class:0x007fdc532c21d0>:0x007fdc5443a610>
    /Users/hoge/work/myruby/hanami_practice/bookshelf/spec/bookshelf/interactors/add_book_spec.rb:8:in `block (2 levels) in <top (required)>'

19 runs, 36 assertions, 0 failures, 1 errors, 1 skips
```

**Comment by cllns** [comment]
Thanks for reporting this! I appreciate it. Can you try `be_successful` instead?

Also, which version of RSpec are you using?

**Comment by sutonea** [comment]
@cllns Thank you!

My Gemfile not included `gem 'rspec'` .

After add that, execute `rspec spec/bookshelf/interactors/add_book_spec.rb`, result was green.

-------------

I want to fix doc :

* Add `'gem 'rspec'` to gemfile
* Modify test command from `rake test` to `rspec`

**Comment by sutonea** [comment]
After install Rspec, other tests failed :(

```
Finished in 0.06351 seconds (files took 1.66 seconds to load)
19 examples, 17 failures, 1 pending
```

Failed test codes are in `Getting Started`.

**Comment by cllns** [comment]
@sutonea Sorry about that. We're in a bit of a transition. The Getting Started guided uses Minitest, but this article was written for RSpec. I'm working on converting the Getting Started guide to RSpec, I think that might be the problem here?

**Comment by sutonea** [comment]
@cllns Thank you!

> I think that might be the problem here?
I think so, too.

I have just noticed :
https://github.com/hanami/hanami.github.io/issues/365

**Comment by AlfonsoUceda** [comment]
@sutonea thank you for the PR, even so I'm going to merge it to fix that problem

**Pull request merged**
