### PR TITLE
Advanon Logo

### PR DESCRIPTION
**Pull request by martintsch**
Like discussed with @marionschleifer ...

### CODE REVIEW

**Comment by jodosha** [comment]
@martintsch Hey and thank you both for this PR and for using Hanami. 💯 
Is this the URL to link, correct? https://www.advanon.com

**Comment by martintsch** [comment]
@jodosha yes perfect! Thanks for making hanami 🥇

**Comment by jodosha** [comment]
@martintsch Hey, sorry the automatic deploy closed this PR. I just recognized this PR was pointing to `master` instead of `build` branch. We use `master` to deploy and `build` for the source code. I'm gonna make another PR for this.

**Comment by jodosha** [comment]
@martintsch I just merged https://github.com/hanami/hanami.github.io/pull/420, which adds Advanon as company to the homepage. Thank you.

**Comment by martintsch** [comment]
@jodosha thanks for putting us on you homepage. Should I create PR for some CSS improvements?
A bit of padding could help...
screen shot 2017-12-04 at 18 20 20

**Comment by jodosha** [comment]
Oh, it looks different locally. Thanks, another PR would help for sure! Please remember to branch from `build`

**Comment by martintsch** [comment]
Here it is https://github.com/hanami/hanami.github.io/pull/421 hopefully that is ok. Using bootstrap utils. Did not want to mess with your CSS ;-)

**Pull request closed without merging**
