### PR TITLE
Structural improvements to overview.md

### PR DESCRIPTION
**Pull request by Nikamura**
It makes more sense for *Rack* description to be before *Actions*.

### CODE REVIEW

**Comment by davydovanton** [comment]
@hanami/core WDYT? I don't see any benefits here but maybe you will see

**Comment by Nikamura** [comment]
at least how the text is formatted, I was confused as you introduced Rack.

> Full Rack integration is great, but the most common endpoint that we'll use in our web applications...

even though it has not been introduced and only follows after *actions*. 
First reading about Rack then about actions makes more sense.

**Comment by davydovanton** [comment]
okay, it looks convincing. Thanks!

**Comment by davydovanton** [comment]
thanks for contribution!

**Pull request merged**
