### PR TITLE
Fixed anchor icon issue #277

### PR DESCRIPTION
**Pull request by eko24ive**

### CODE REVIEW

**Comment by davydovanton** [comment]
hey @eko24ive, thanks for contribution 👍 
Could you add some screenshots with new changes? Thanks!

**Comment by eko24ive** [comment]
sure, @davydovanton
I'll be at the office in a few minutes - I'll make some screenshots and gifs

**Comment by eko24ive** [comment]
@davydovanton I've noticed one minor issue with my PR - anchor link is dissapearing if mouse runs through some kind of gap:
image

I've fixed that too, here is where how it looks now:
image

Also it shown when mouse is hovering parent link:
image

**Comment by eko24ive** [comment]
@davydovanton any updates ?

**Comment by eko24ive** [comment]
You're welcome !
@davydovanton I think I forgot to test this changes on generic mobile devices, should I do so ?

**Comment by davydovanton** [comment]
yep. Please, test it too @eko24ive 👍

**Comment by eko24ive** [comment]
Ok, I'll reply today/tomorrow

**Pull request merged**
