### PR TITLE
set database to postgresql in download, develop, deploy in 5 minutes section

### PR DESCRIPTION
**Pull request by bbonislawski**
Setting db to postgresql fixes problems with deploy on heroku. Problem mentioned in #269

### CODE REVIEW

**Comment by oana-sipos** [comment]
Hey @bbonislawski, thanks for the suggestion. I can see your point, but instead of this approach, I would propose to mention that ”remember that sqlite does not work on Heroku, thus use postgresql (or another DB) for this task”. I can understand your point of frustration for beginners, but as frustrated as I was back then, it was still a very important lesson I had to learn. My 2 cents.

p.s. There is already a comment on the getting started guide which suggests to generate a project using a different DB for real projects: http://hanamirb.org/guides/getting-started/

**Comment by bbonislawski** [comment]
I understand decision for sqlite in guide, but user sees `Download, Develop, Deploy in 5 minutes. ` on home page and then he will see, that it won't work even after copying commands from home page. It's not a problem for me but could be problem for newcomerse.

**Comment by cllns** [comment]
@oana-sipos I disagree, I think this PR should be merged. We have the code there so people could copy & paste or enter as-in. We should provide the exact commands that will work. The comment on the Getting Started guide is good and necessary, but this is a different example. Thoughts?

**Comment by b264** [comment]
I definitely think this should be merged

**Comment by AlfonsoUceda** [comment]
@bbonislawski mysql works on Heroku? I think we could use the two version
```ruby

**Comment by cllns** [comment]
@AlfonsoUceda I think we should keep it as simple as possible, and not give people the option.
It looks like it's not supported very well on Heroku. [Their guide](https://devcenter.heroku.com/articles/heroku-mysql) is about migrating to Postgres, though they do offer 3rd party addons for MySQL.

**Comment by AlfonsoUceda** [comment]
@cllns then that is enough ;)

**Pull request merged**
