### PR TITLE
Add special page with status of all hanami parts

### PR DESCRIPTION
**Pull request by davydovanton**
I found this idea on [ROM site](http://rom-rb.org/status/). Also I'll be very glad to any comments and suggestions 💚 

### Desktop
screenshot 2016-05-25 01 59 56

### Mobile
screenshot 2016-05-25 02 00 04

/cc @hanami/core-team and @hanami/contributors

### CODE REVIEW

**Comment by joneslee85** [comment]
I ❤️ this

**Comment by pascalbetz** [comment]
nice.

**Comment by jodosha** [comment]
@davydovanton I like the idea. 👍 

But we should link it elsewhere, not from the main navigation. There will probably be upcoming links over there, so better to keep it small for now.

**Comment by davydovanton** [comment]
@jodosha what about footer?

**Comment by davydovanton** [comment]
@jodosha I putted status link to footer, what do you think is it better now?

**Comment by jodosha** [comment]
@davydovanton much better, thanks! 👍

**Comment by davydovanton** [comment]
thanks for merge 🎉

**Pull request merged**
