### PR TITLE
Update shared view guide

### PR DESCRIPTION
**Pull request by davydovanton**
Reference to gitter disscussion https://gitter.im/hanami/chat?at=58f87d64f22385553d5b75b8

### CODE REVIEW

**Comment by TiteiKo** [comment]
Given the example, why would you need to require the file from the layout? You would need to require it in `apps/web/application.rb`, but that's all.

**Comment by davydovanton** [comment]
@TiteiKo good idea, @hanami/core WDYT?

**Comment by oana-sipos** [comment]
👍  to @TiteiKo.

**Comment by marionschleifer** [comment]
I agree, @TiteiKo 🥇

**Comment by davydovanton** [comment]
@TiteiKo I updated example. Could you check this PR again?

**Comment by TiteiKo** [comment]
So I looked at the entire file, and it looks like instead of making a new paragraph, you could just change the previous one:

```diff
- Then we include it in all the views of our application, via view.prepare.
+ Then we can load the file and include the module in **all** the views of our application, using view.prepare.

# apps/web/application.rb
+ require_relative './views/accept_json.rb'

module Web
  class Application < Hanami::Application
    configure do
      # ...
      view.prepare do
        include Web::Views::AcceptJson
      end
    end
  end
end
```

**Comment by davydovanton** [comment]
@TiteiKo 
screenshot 2017-06-14 01 57 05

**Comment by davydovanton** [comment]
@TiteiKo I'll merge it. If you have some issue I'll fix it in other PR 😊

**Comment by TiteiKo** [comment]
What I was saying was that instead of having 2 incomplete code blocks, you could just make one that would have all the informations. Note that there's already a warning below stating that the code included would be available in all the views of the application.

You can see an example of the same explications made in 1 code block in [the actions share code guide](http://hanamirb.org/guides/actions/share-code/) (paragraph Module Inclusion)

**Comment by davydovanton** [comment]
@TiteiKo nice point. Could you create PR for fix it? Thanks!

**Pull request merged**
