### PR TITLE
Display guides data for specific version

### PR DESCRIPTION
**Pull request by davydovanton**
ccvnlqklb4

### CODE REVIEW

**Review by jodosha — CHANGES_REQUESTED** [review]
The changes are looking good for the versioned guides, but by visiting `/guides` I get a 404.

**Comment by davydovanton** [comment]
@jodosha thanks for QA. I'll check it 👍

**Comment by davydovanton** [comment]
@jodosha I think the problem in your local build. Remember that we need to copy 1.0 guides folder for displaying all `/guides` pages (I did it for old links). 

Could you try to run this code: 
https://github.com/hanami/hanami.github.io/blob/build/bin/site#L15

and check your local build again?

**Review by jodosha — COMMENTED** [review]
@davydovanton By executing

```shell
cp -fR ./source/guides/1.0/* ./source/guides
```

and then

```shell
bin/site develop
```

It works as expected.. but:

```shell
git status
On branch feature/guides-navigation-by-version
Your branch is up-to-date with 'origin/feature/guides-navigation-by-version'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	source/guides/actions/
	source/guides/architecture/
	source/guides/assets/
	source/guides/command-line/
	source/guides/getting-started.md
	source/guides/helpers/
	source/guides/index.md
	source/guides/mailers/
	source/guides/migrations/
	source/guides/models/
	source/guides/projects/
	source/guides/routing/
	source/guides/validations/
	source/guides/views/

nothing added to commit but untracked files present (use "git add" to track)
```

Is this normal?

**Comment by AlfonsoUceda** [comment]
Superseed by https://github.com/hanami/hanami.github.io/pull/399

**Comment by AlfonsoUceda** [comment]
@jodosha that happens to me but I think that is related with another thing, I'll try to take a look when I can.

**Pull request closed without merging**
