### PR TITLE
Bump middleman to v4

### PR DESCRIPTION
**Pull request by joneslee85**
Keep middleman up to date

## Known issues to be addressed

* [ ] deployment script does not work ([patch](https://github.com/middleman-contrib/middleman-deploy/pull/133) is waiting to be merged upstream)

### CODE REVIEW

**Comment by joneslee85** [comment]
We do, I just comment it out temporarily

**Comment by marionschleifer** [comment]
Hey guys, what's the status of this PR? @joneslee85 could you comment this line in the Gemfile back in? Or is there a reason why it should be commented out?

**Comment by oana-sipos** [comment]
Just a kind reminder, @joneslee85 :)

**Comment by AlfonsoUceda** [comment]
@davydovanton @oana-sipos check the description, it seems the deploy script doesn't work with middleman 4, I think we should migrate to jekyll >_<

**Comment by AlfonsoUceda** [comment]
Folks I'm going to close this PR it seems middleman-deploy is stale, we'll think about this.

**Pull request closed without merging**
