### PR TITLE
Add notes about removing from `spec` dir

### PR DESCRIPTION
**Pull request by Pistos**
And also reformat the listing.

### CODE REVIEW

**Comment by cllns** [comment]
Thanks for this @Pistos!

I added a commit that changes the PR significantly, since I think we should focus this section on only removing `hanami-model`, and leave removing Mailers to the reader. I know that was already there before, but what do you think of my changes in general?

**Comment by Pistos** [comment]
Thank you for your attention to this PR.

**Comment by kaikuchn** [comment]
looks good to me!

**Comment by cllns** [comment]
Thanks @Pistos & @kaikuchn!

**Pull request merged**
