### PR TITLE
Removed misleading sentence from opening paragraph

### PR DESCRIPTION
**Pull request by graywolf**
The sentence I removed gived me impression that I should learn rails first and then come back to hanami. From reddit I understand that this is not correct. I'm intersted in hanami even when I never touched rails.

### CODE REVIEW

**Comment by davydovanton** [comment]
Sorry, but I don't see any negative in this sentence.
It's about changes your mind and not about rails. Also, I don't find any `rails` matches on this page, that's why I have a question: why do you think that this about rails and not Sinatra or something else?

**Comment by cllns** [comment]
I see both of your points. I think this line is important, but it can be phrase better. How about something like:

> Over time, we build expectations about how things _should_ be, and it can be painful to change. But **without change, there is no challenge** and without challenge, there is no growth.

?

**Comment by graywolf** [comment]
@davydovanton 
> why do you think that this about rails and not Sinatra or something else?

sinatra isn't 10 years old yet. since rails is about 11, I reached the impression that it was reference to rails. but true, I might be wrong, what is the "after **10** years" refering to then?

@cllns 
> I see both of your points. I think this line is important, but it can be phrased better.

I like it, I'll update the pull request.

**Comment by AlfonsoUceda** [comment]
@graywolf thanks for this PR, folks I like it this PR what do you think @hanami/core ?

**Comment by davydovanton** [comment]
much better now 👍

**Comment by cllns** [comment]
👍

**Comment by davydovanton** [comment]
@jodosha could you check this? Thanks!

**Comment by davydovanton** [comment]
thanks for this contribution 👏

**Pull request merged**
