### PR TITLE
remove bundle folder

### PR DESCRIPTION
**Pull request by tudorpavel**
Relates to: #314, #140

I activated Travis on my fork and the middleman build passed without the `bundle` folder. @joneslee85, was there any other reason to commit the `bundle` folder?

### CODE REVIEW

**Comment by cllns** [comment]
Looks like we might have to upgrade to middleman 4, in order to pin the right version for the sitemap gem? https://github.com/Aupajo/middleman-search_engine_sitemap/issues/5#issuecomment-200246974

**Comment by tudorpavel** [comment]
> Looks like we might have to upgrade to middleman 4

Yep, I saw that but I wasn't sure how to test everything after the upgrade. From the previous PR #140, I assumed the `bundle` folder was added only because of problems on Travis, so that's why I tried the build without it on Travis and the [sitemap was generated successfully](https://travis-ci.org/tudorpavel/hanami.github.io/builds/226071960#L529).

I think @joneslee85 is best equipped to confirm that the `bundle` folder was added only because of Travis.

**Comment by cllns** [comment]
We use Travis to build the static-site :/

**Comment by tudorpavel** [comment]
Yup, I know and I'm saying the sitemap build worked on Travis on my fork without the bundle folder, so I think it's not necessary to have the bundle folder in git anymore.

**Comment by cllns** [comment]
@davydovanton Can you look into this? Would certainly make the build process simpler, to remove the local copies of gems in the `bundle/` folder

**Comment by AlfonsoUceda** [comment]
Closing this PR because it is stale.

**Pull request closed without merging**
