### PR TITLE
Create anchors like in github

### PR DESCRIPTION
**Pull request by davydovanton**
6sy7z8lfzc

/cc @hanami/core-team and @hanami/contributors

### CODE REVIEW

**Comment by jodosha** [comment]
@davydovanton Wow this is 💯

**Comment by davydovanton** [comment]
yep, sometimes I need to send link to special part of guide 😄

**Comment by jodosha** [comment]
@davydovanton yup, absolutely. It helps a lot!

**Comment by pascalbetz** [comment]
Nice!

**Comment by cllns** [comment]
awesome @davydovanton ! gif screencast too 👌

**Pull request merged**
