### PR TITLE
Adds 'is' to 'Here how Hanami handles' in basic usage guides

### PR DESCRIPTION
**Pull request by philnash**

### CODE REVIEW

**Comment by marionschleifer** [comment]
Hi @philnash, thank you so much for your contribution! Could you send me your postal address to marion.schleifer@gmail.com? I would love to send you some stickers :-)

**Comment by philnash** [comment]
Hey @marionschleifer, thanks for the offer I'm just glad to help, so don't worry about sending things to me! I am writing a couple of blog posts about Hanami though, so would love if they could be shared when I'm done!

**Comment by marionschleifer** [comment]
Hi @philnash, of course, we will share your blogposts! 😃 Just let me know via Twitter (@rubydwarf) or email (marion.schleifer@gmail.com) when you're done and I will make sure we'll share them 👍

**Pull request merged**
