### PR TITLE
Fix font sizes and weights and migrate from Roboto to Overpass

### PR DESCRIPTION
**Pull request by kbrgl**
Fixes issue #235, making fonts in the docs much more pleasant and readable.

Summary of changes:
* Change font used from Roboto to Overpass
* Fix font sizes and weights
* Enable font smoothing on WebKit based browsers (results in more crisp and clear fonts)
* Change code background color

### CODE REVIEW

**Comment by kbrgl** [comment]
Screenshots:
screen shot 2017-03-04 at 12 14 24 pm
screen shot 2017-03-04 at 12 14 16 pm
screen shot 2017-03-04 at 12 14 10 pm
screen shot 2017-03-04 at 12 14 02 pm
screen shot 2017-03-04 at 12 13 50 pm

**Comment by kbrgl** [comment]
Sorry, closed accidentally 👅

GitHub should make this button harder to press!

**Comment by cllns** [comment]
Oooh, I like this. :)

I think it could be nice to merge this when we release `v1.0.0` proper, as a little visual docs bonus. OK with merging it sooner too though. Thanks for doing this! 🌸

**Comment by AlfonsoUceda** [comment]
@kbrgl thanks for this PR, I really like it. @cllns I think we don't need to wait until v1.0.0 stable, what do you think @hanami/core

**Pull request merged**
