### PR TITLE
Added Utils Hanami::Interactor explanation with a real-world example. Indented some sloppily-formatted code.

### PR DESCRIPTION
**Pull request by vladdypwnz**
This is in reference to issue #215 .

This commit is useful because it adds documentation to the Guide about the Interactor, as there is no documentation on the Interactor at all besides the Rdoc (it's a little arcane and doesn't explain some critical methods). I've also cleaned up some sloppily pasted code.

The explanation is a bit long because the Interactor is a little bit tricky. 

However, I've cut about 50-75% from my original draft thanks to @cllns advice, let's see if we can make it even more palatable.

### CODE REVIEW

**Comment by cllns** [comment]
Thanks for working on this!

I'd like to see a simpler example, without `HTTParty`, `ReCaptcha`, or `Dry::Validation.Schema`. The example you gave is a good real-world example, but it's too complicated in my opinion. There's a lot going on. I think it's better to just focus on the `Interactor` itself.

The `SignUp` example here: http://www.rubydoc.info/gems/hanami-utils/Hanami/Interactor/Interface is nice & simple. (Would like to see one with `Book` instead though, for this guide)

We wouldn't want to encourage people to use `home#submit`. Instead, that should be `book#create`.

In general, I don't think we need to explain everything about Interactors. I'm thinking 3 sections: **Basic Information**, **Interface**, **Result**. The first would provide a basic example, and explain some benefits of this approach. The **Interface** section could explain `initialize`, `call` and `valid?`. The **Result** section could talk about `errors` and `success?`. 

And a very tiny thing, but we should use the `error!` style instead of `error!()`.

Let me know if you want me to take this over from here, or if you want to continue working on this!

**Comment by vladdypwnz** [comment]
Feel free to take over if you have the time, it might be faster if you do it. I used an example of something I myself use. 

I disagree that we shouldn't explain everything about it - rdoc makes no mention for example, that `error()` will not stop execution. At least, not in the Interface example given or that `throw`s are suppressed inside `call`.

Since you have more experience with the tone of the Guide though, maybe it's best if you take over.

**Comment by cllns** [comment]
Ok! 

If you've found errors or omissions in the RDoc, please submit a PR to `hanami/utils` to fix them :) The RDocs should be authoritative.

**Comment by vladdypwnz** [comment]
Sounds good Sean.

This is probably a little off-topic but is there a Guide on using `Dry::Validation.Schema` at all in the Hanami Guide? There's the [new validation syntax](http://hanamirb.org/blog/2016/07/22/announcing-hanami-080.html#new-validations-syntax) kind of based on it. Would a guide on either be useful or did I already miss it in the guide?

**Comment by cllns** [comment]
There's a guide for using `hanami/validations`, in the context of parameters: http://hanamirb.org/guides/actions/parameters/#usage

Going to close this PR. Thanks for working on this, will definitely be using this and our discussion as a basis for the PR I'll open. I'll make sure to get your input on it too :) 🌸

**Pull request closed without merging**
